apiVersion: apps/v1
kind: Deployment
metadata:
  name: bulletin-board
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: bulletin-board
  template:
    metadata:
      labels:
        app: bulletin-board
    spec:
      containers:
        - name: app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
