apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: bulletin
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:postgresql://bulletin-db:6432/app
  SPRING_DATASOURCE_USERNAME: app
  SPRING_DATASOURCE_PASSWORD: Qwerty123qaz
