apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: bulletin
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:postgresql://<TF_DB_HOST>:6432/<TF_DB_NAME>
  SPRING_DATASOURCE_USERNAME: <TF_DB_USER>
  SPRING_DATASOURCE_PASSWORD: <TF_DB_PASSWORD>