apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bulletin-ingress
  namespace: bulletin
spec:
  ingressClassName: nginx
  rules:
    - host: bulletin.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bulletin-svc
                port:
                  number: 80
